version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000" # Grafana web UI
    volumes:
      - grafana-storage:/var/lib/grafana # Persistent storage for Grafana data
      - grafana-plugins:/var/lib/grafana/plugins # Persistent storage for plugins data
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
      - GF_SERVER_PROTOCOL=http
      - GF_SERVER_DOMAIN=grafana
      - GF_SERVER_HTTP_PORT=3000
      - GF_SERVER_ROOT_URL=http://grafana:3000/
      - GF_SERVER_SERVE_FROM_SUB_PATH=false
volumes:
  grafana-storage:
  grafana-plugins:
