version: "3.7"

services:
  axigen:
    image: axigen/axigen:latest
    container_name: axigen
    ports:
      - "6443:443"     # WebMail HTTPS
      - "7443:9443"   # Secure Admin/Web UI
      - "993:993"     # IMAPS
      - "995:995"     # POP3S
      - "25:25"       # SMTP
      - "465:465"     # SMTPS
      - "9000:9000"   # WebAdmin (HTTP)
      - "7000:7000"   # Internal (Axigen cluster/diagnostics)
    volumes:
      - /home/srcadm/apps/axigen/data:/var/axigen
      - /home/srcadm/apps/axigen/license:/opt/axigen/license
    restart: unless-stopped 
    hostname: dc01plpmon003.rphomelab.in
