version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-controller
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - /home/srcadm/apps/jenkins-controller/data:/var/jenkins_home
    restart: unless-stopped
